"""Added party_size column to RestaurantBooking model

Revision ID: 10da50afeb65
Revises: 
Create Date: 2024-02-05 09:42:15.360929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10da50afeb65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('party_size', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_bookings', schema=None) as batch_op:
        batch_op.drop_column('party_size')

    # ### end Alembic commands ###
